### ISSUE TITLE
Training in Google Colaboratory crashing

### ISSUE THREAD

**Issue by LAnastasiia** [ManuGar/UFOD#31]
Training in Google Colaboratory crashing with `RuntimeError: `set_session` is not available when TensorFlow is executing eagerly`

**Comment by LAnastasiia** [comment]
fixed it locally by adding `tf.compat.v1.disable_eager_execution()` line in [train.py](https://github.com/ManuGar/UFOD/blob/7a2f0cbfaaf6b603496b5679cb38cc54abe1143a/kerasfcos/train.py).

Looks like there's external users are not allowed to create a branch & a pull request in this repo, so you might want to add it yourself if you think it's a good fix.

**Comment by joheras** [comment]
Thanks. We have fixed that problem. 
Thank you for reporting it.
